name: Deploy static site to Azure App Service - apiproyecto5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8102682221A54CE4968F0D9DAF79353B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E8680124BD64CBF93E5ADB9CCB07F7D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_59FAD273484F47E6B979CD270392A4C1 }}

      - name: Deploy static files to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apiproyecto5'
          slot-name: 'Production'
          package: .




